apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-manager
  template:
    metadata:
      labels:
        app: k8s-manager
    spec:
      serviceAccountName: k8s-manager-sa
      containers:
      - name: k8s-manager
        image: k8s-manager:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: k8s-manager-service
spec:
  selector:
    app: k8s-manager
  ports:
  - port: 8080
    targetPort: 8080
  type: NodePort
