apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-app3
  template:
    metadata:
      labels:
        app: python-app3
    spec:
      containers:
      - name: python-app3
        image: python-k8s-app3:latest
        env:
        - name: APP_NAME
          value: "app3"
        - name: NATS_URL
          value: "nats://nats-service:4222"
